services:
  frontend:
    build:
      context: ./triviafrontend
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./triviabackend
    ports:
      - "8080:8080"
    depends_on:
      - frontend
